import { translate } from "app/i18n"

export const suwar = [
    // [start, ayas, order, rukus, name, tname, ename, type]
    [0, "", "", "", ""],
    [7, "الفاتحة", "Al-Faatiha", "The Opening", "Meccan"],
    [286, "البقرة", "Al-Baqara", "The Cow", "Medinan"],
    [200, "آل عمران", "Aal-i-Imraan", "The Family of Imraan", "Medinan"],
    [176, "النساء", "An-Nisaa", "The Women", "Medinan"],
    [120, "المائدة", "Al-Maaida", "The Table", "Medinan"],
    [165, "الأنعام", "Al-An'aam", "The Cattle", "Meccan"],
    [206, "الأعراف", "Al-A'raaf", "The Heights", "Meccan"],
    [75, "الأنفال", "Al-Anfaal", "The Spoils of War", "Medinan"],
    [129, "التوبة", "At-Tawba", "The Repentance", "Medinan"],
    [109, "يونس", "Yunus", "Jonas", "Meccan"],
    [123, "هود", "Hud", "Hud", "Meccan"],
    [111, "يوسف", "Yusuf", "Joseph", "Meccan"],
    [43, "الرعد", "Ar-Ra'd", "The Thunder", "Medinan"],
    [52, "ابراهيم", "Ibrahim", "Abraham", "Meccan"],
    [99, "الحجر", "Al-Hijr", "The Rock", "Meccan"],
    [128, "النحل", "An-Nahl", "The Bee", "Meccan"],
    [111, "الإسراء", "Al-Israa", "The Night Journey", "Meccan"],
    [110, "الكهف", "Al-Kahf", "The Cave", "Meccan"],
    [98, "مريم", "Maryam", "Mary", "Meccan"],
    [135, "طه", "Taa-Haa", "Taa-Haa", "Meccan"],
    [112, "الأنبياء", "Al-Anbiyaa", "The Prophets", "Meccan"],
    [78, "الحج", "Al-Hajj", "The Pilgrimage", "Medinan"],
    [118, "المؤمنون", "Al-Muminoon", "The Believers", "Meccan"],
    [64, "النور", "An-Noor", "The Light", "Medinan"],
    [77, "الفرقان", "Al-Furqaan", "The Criterion", "Meccan"],
    [227, "الشعراء", "Ash-Shu'araa", "The Poets", "Meccan"],
    [93, "النمل", "An-Naml", "The Ant", "Meccan"],
    [88, "القصص", "Al-Qasas", "The Stories", "Meccan"],
    [69, "العنكبوت", "Al-Ankaboot", "The Spider", "Meccan"],
    [60, "الروم", "Ar-Room", "The Romans", "Meccan"],
    [34, "لقمان", "Luqman", "Luqman", "Meccan"],
    [30, "السجدة", "As-Sajda", "The Prostration", "Meccan"],
    [73, "الأحزاب", "Al-Ahzaab", "The Clans", "Medinan"],
    [54, "سبإ", "Saba", "Sheba", "Meccan"],
    [45, "فاطر", "Faatir", "The Originator", "Meccan"],
    [83, "يس", "Yaseen", "Yaseen", "Meccan"],
    [182, "الصافات", "As-Saaffaat", "Those drawn up in Ranks", "Meccan"],
    [88, "ص", "Saad", "The letter Saad", "Meccan"],
    [75, "الزمر", "Az-Zumar", "The Groups", "Meccan"],
    [85, "غافر", "Al-Ghaafir", "The Forgiver", "Meccan"],
    [54, "فصلت", "Fussilat", "Explained in detail", "Meccan"],
    [53, "الشورى", "Ash-Shura", "Consultation", "Meccan"],
    [89, "الزخرف", "Az-Zukhruf", "Ornaments of gold", "Meccan"],
    [59, "الدخان", "Ad-Dukhaan", "The Smoke", "Meccan"],
    [37, "الجاثية", "Al-Jaathiya", "Crouching", "Meccan"],
    [35, "الأحقاف", "Al-Ahqaf", "The Dunes", "Meccan"],
    [38, "محمد", "Muhammad", "Muhammad", "Medinan"],
    [29, "الفتح", "Al-Fath", "The Victory", "Medinan"],
    [18, "الحجرات", "Al-Hujuraat", "The Inner Apartments", "Medinan"],
    [45, "ق", "Qaaf", "The letter Qaaf", "Meccan"],
    [60, "الذاريات", "Adh-Dhaariyat", "The Winnowing Winds", "Meccan"],
    [49, "الطور", "At-Tur", "The Mount", "Meccan"],
    [62, "النجم", "An-Najm", "The Star", "Meccan"],
    [55, "القمر", "Al-Qamar", "The Moon", "Meccan"],
    [78, "الرحمن", "Ar-Rahmaan", "The Beneficent", "Medinan"],
    [96, "الواقعة", "Al-Waaqia", "The Inevitable", "Meccan"],
    [29, "الحديد", "Al-Hadid", "The Iron", "Medinan"],
    [22, "المجادلة", "Al-Mujaadila", "The Pleading Woman", "Medinan"],
    [24, "الحشر", "Al-Hashr", "The Exile", "Medinan"],
    [13, "الممتحنة", "Al-Mumtahana", "She that is to be examined", "Medinan"],
    [14, "الصف", "As-Saff", "The Ranks", "Medinan"],
    [11, "الجمعة", "Al-Jumu'a", "Friday", "Medinan"],
    [11, "المنافقون", "Al-Munaafiqoon", "The Hypocrites", "Medinan"],
    [18, "التغابن", "At-Taghaabun", "Mutual Disillusion", "Medinan"],
    [12, "الطلاق", "At-Talaaq", "Divorce", "Medinan"],
    [12, "التحريم", "At-Tahrim", "The Prohibition", "Medinan"],
    [30, "الملك", "Al-Mulk", "The Sovereignty", "Meccan"],
    [52, "القلم", "Al-Qalam", "The Pen", "Meccan"],
    [52, "الحاقة", "Al-Haaqqa", "The Reality", "Meccan"],
    [44, "المعارج", "Al-Ma'aarij", "The Ascending Stairways", "Meccan"],
    [28, "نوح", "Nooh", "Noah", "Meccan"],
    [28, "الجن", "Al-Jinn", "The Jinn", "Meccan"],
    [20, "المزمل", "Al-Muzzammil", "The Enshrouded One", "Meccan"],
    [56, "المدثر", "Al-Muddaththir", "The Cloaked One", "Meccan"],
    [40, "القيامة", "Al-Qiyaama", "The Resurrection", "Meccan"],
    [31, "الانسان", "Al-Insaan", "Man", "Medinan"],
    [50, "المرسلات", "Al-Mursalaat", "The Emissaries", "Meccan"],
    [40, "النبإ", "An-Naba", "The Announcement", "Meccan"],
    [46, "النازعات", "An-Naazi'aat", "Those who drag forth", "Meccan"],
    [42, "عبس", "Abasa", "He frowned", "Meccan"],
    [29, "التكوير", "At-Takwir", "The Overthrowing", "Meccan"],
    [19, "الإنفطار", "Al-Infitaar", "The Cleaving", "Meccan"],
    [36, "المطففين", "Al-Mutaffifin", "Defrauding", "Meccan"],
    [25, "الإنشقاق", "Al-Inshiqaaq", "The Splitting Open", "Meccan"],
    [22, "البروج", "Al-Burooj", "The Constellations", "Meccan"],
    [17, "الطارق", "At-Taariq", "The Morning Star", "Meccan"],
    [19, "الأعلى", "Al-A'laa", "The Most High", "Meccan"],
    [26, "الغاشية", "Al-Ghaashiya", "The Overwhelming", "Meccan"],
    [30, "الفجر", "Al-Fajr", "The Dawn", "Meccan"],
    [20, "البلد", "Al-Balad", "The City", "Meccan"],
    [15, "الشمس", "Ash-Shams", "The Sun", "Meccan"],
    [21, "الليل", "Al-Lail", "The Night", "Meccan"],
    [11, "الضحى", "Ad-Dhuhaa", "The Morning Hours", "Meccan"],
    [8, "الشرح", "Ash-Sharh", "The Consolation", "Meccan"],
    [8, "التين", "At-Tin", "The Fig", "Meccan"],
    [19, "العلق", "Al-Alaq", "The Clot", "Meccan"],
    [5, "القدر", "Al-Qadr", "The Power, Fate", "Meccan"],
    [8, "البينة", "Al-Bayyina", "The Evidence", "Medinan"],
    [8, "الزلزلة", "Az-Zalzala", "The Earthquake", "Medinan"],
    [11, "العاديات", "Al-Aadiyaat", "The Chargers", "Meccan"],
    [11, "القارعة", "Al-Qaari'a", "The Calamity", "Meccan"],
    [8, "التكاثر", "At-Takaathur", "Competition", "Meccan"],
    [3, "العصر", "Al-Asr", "The Declining Day, Epoch", "Meccan"],
    [9, "الهمزة", "Al-Humaza", "The Traducer", "Meccan"],
    [5, "الفيل", "Al-Fil", "The Elephant", "Meccan"],
    [4, "قريش", "Quraish", "Quraysh", "Meccan"],
    [7, "الماعون", "Al-Maa'un", "Almsgiving", "Meccan"],
    [3, "الكوثر", "Al-Kawthar", "Abundance", "Meccan"],
    [6, "الكافرون", "Al-Kaafiroon", "The Disbelievers", "Meccan"],
    [3, "النصر", "An-Nasr", "Divine Support", "Medinan"],
    [5, "المسد", "Al-Masad", "The Palm Fibre", "Meccan"],
    [4, "الإخلاص", "Al-Ikhlaas", "Sincerity", "Meccan"],
    [5, "الفلق", "Al-Falaq", "The Dawn", "Meccan"],
    [6, "الناس", "An-Naas", "Mankind", "Meccan"],
  ]

  export const schoolLevel = [
    {
      label: translate("file.not_set"),
      value: null,
    },
    {
      label: translate("file.primary_1"),
      value: "primary_1",
    },
    {
      label: translate("file.primary_2"),
      value: "primary_2",
    },
    {
      label: translate("file.primary_3"),
      value: "primary_3",
    },
    {
      label: translate("file.primary_4"),
      value: "primary_4",
    },
    {
      label: translate("file.primary_5"),
      value: "primary_5",
    },
    {
      label: translate("file.middle_1"),
      value: "middle_1",
    },
    {
      label: translate("file.middle_2"),
      value: "middle_2",
    },
    {
      label: translate("file.middle_3"),
      value: "middle_3",
    },
    {
      label: translate("file.middle_4"),
      value: "middle_4",
    },
    {
      label: translate("file.secondary_1"),
      value: "secondary_1",
    },
    {
      label: translate("file.secondary_2"),
      value: "secondary_2",
    },
    {
      label: translate("file.secondary_3"),
      value: "secondary_3",
    },
    {
      label: translate("file.university"),
      value: "university",
    },

  ]



  export const eligibleForSport = [
    {
      label: translate("file.not_set"),
      value: null,
    },
    {
      label: translate("file.notEligible"),
      value: "0",
    },
    {
      label: translate("file.eligible"),
      value: "1",
    },
 

  ]

  export const subscriptions = [
    {
      label: translate("file.not_set"),
      value: null,
    },
    {
      label: translate("file.contributor"),
      value: 'contributor',
    },
    {
      label: translate("file.not_contributor"),
      value: "not_contributor",
    },
    {
      label: translate("file.can_contribute_more"),
      value: "can_contribute_more",
    },

  ]